logging:
  level:
    root: info
    io.lzz: debug

spring:
  batch:
    initialize-schema: never
    job:
      enabled: false
      
  activemq:
    in-memory: false
    broker-url: tcp://localhost:61616
