logging:
  level:
    root: warn
    io.lzz: debug
    
spring:      
  activemq:
    in-memory: false
    broker-url: tcp://localhost:61616

  batch:
    initialize-schema: always
    job:
      enabled: false

  datasource:
    url: jdbc:h2:./out/batch.db;AUTO_SERVER=TRUE

  h2:
    console:
      enabled: true
      
  jpa:
    hibernate:
      ddl-auto: drop-create
      
      