logging:
#  pattern:
#    console: '%d{HH:mm:ss.SSS} -%5p ${PID:- } --- [%15.15t,%T] %-40.40c{1.}(%L,%M) : %m%n%xwEx'
    
  level:
    root: warn
    io.lzz: warn
    
spring:      
  activemq:
    in-memory: false
    broker-url: tcp://localhost:61616

  batch:
    initialize-schema: always
    job:
      enabled: false

  datasource:
    url: jdbc:h2:./tmp/batch.db;AUTO_SERVER=TRUE
    username: sa

  h2:
    console:
      enabled: true
      
  jpa:
    hibernate:
      ddl-auto: create
      
    show-sql: true
    
    