logging:
  level:
    root: info
    io.lzz: debug
    
spring:      
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true # 为false时bean转换会报类找不到异常

  batch:
    initialize-schema: never
    job:
      enabled: false

  datasource:
    url: jdbc:h2:./tmp/batch.db;AUTO_SERVER=TRUE
    username: sa

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
