# 自定义配置，app.xxx...
#app:
#  datasource:
#    batch:
#      url: jdbc:h2:./tmp/batch.db;AUTO_SERVER=TRUE
#      jdbc-url: jdbc:h2:./tmp/batch.db;AUTO_SERVER=TRUE
#      username: sa
#    biz:
#      url: jdbc:h2:./tmp/biz.db;AUTO_SERVER=TRUE
#      jdbc-url: jdbc:h2:./tmp/biz.db;AUTO_SERVER=TRUE
#      username: sa
logging:
  level:
    root: info
    sql: info
    org.springframework.batch: info
    io.lzz: debug
    io.lzz.demo.spring.batch.repository: trace
#    org.hibernate.SQL: debug
#    org.hibernate.engine.QueryParameters: debug
#    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  activemq:
    in-memory: true
#    broker-url: tcp://localhost:61616
    packages:
      trust-all: true # 为false时bean转换会报类找不到异常

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
#    url: jdbc:h2:./tmp/biz.db;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:test_mem
    username: sa
#Embedded (local) connection	jdbc:h2:[file:][<path>]<databaseName>
#                               jdbc:h2:~/test
#                               jdbc:h2:file:/data/sample
#                               jdbc:h2:file:C:/data/sample (Windows only)
#
#In-memory (private)	jdbc:h2:mem:
#In-memory (named)	    jdbc:h2:mem:<databaseName>
#                       jdbc:h2:mem:test_mem
  h2:
    console:
      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

