# 自定义配置，app.xxx...
app:
  datasource:
    batch:
      url: jdbc:h2:./tmp/batch.db;AUTO_SERVER=TRUE
      jdbc-url: jdbc:h2:./tmp/batch.db;AUTO_SERVER=TRUE
      username: sa
    biz:
      url: jdbc:h2:./tmp/biz.db;AUTO_SERVER=TRUE
      jdbc-url: jdbc:h2:./tmp/biz.db;AUTO_SERVER=TRUE
      username: sa

logging:
  level:
    root: info
    sql: trace
    org.springframework.batch: trace
    io.lzz: debug
    
spring:      
  activemq:
    in-memory: true
#    broker-url: tcp://localhost:61616
    packages:
      trust-all: true # 为false时bean转换会报类找不到异常

  batch:
    initialize-schema: always
    job:
      enabled: false

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
