# 自定义配置，app.xxx...
app:
  datasource:
    primary:
      url: jdbc:h2:./tmp/primary.db;AUTO_SERVER=TRUE
      jdbc-url: jdbc:h2:./tmp/primary.db;AUTO_SERVER=TRUE
      username: sa
    secondary:
      url: jdbc:h2:./tmp/secondary.db;AUTO_SERVER=TRUE
      jdbc-url: jdbc:h2:./tmp/secondary.db;AUTO_SERVER=TRUE
      username: sa

logging:
  level:
    root: info
    sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    io.lzz: debug
    
spring:      
  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    
