logging:
  level:
    root: info
    sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    io.lzz: debug
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_test
    username: root
    password: 123456

  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

