logging:
  level:
    root: info
    web: trace
    sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    io.lzz: debug
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro #?rewriteBatchedStatements=true
    username: root
#    password: 123456
    hikari:
      maximum-pool-size: 16
      connection-test-query: select 1 from tb_user
      
#
#  jpa:
#    properties:
#      hibernate.format_sql: true
#      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true

# @MapperScan 作用于启动类或者配置类上， mapper接口类的位置
# type-aliases-package，实体类位置
# mapper-locations，mapper.xml位置
# 以上3个都不能少
mybatis:
  type-aliases-package: io.lzz.demo.rbac.shiro.entity
  mapper-locations: 
    - classpath:io/lzz/demo/rbac/shiro/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

  
  
  