debug: false
logging:
  level:
    root: info
    io.lzz: debug

spring:
  activemq:
    broker-url: tcp://localhost:61616 #?jms.prefetchPolicy.queuePrefetch=1000
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
# spring boot 2.1.x dependency to org.messaginghub:pooled-jms
#    pool:
#      enabled: false
#      max-connections: 4
#      time-between-expiration-check: 10s
#      idle-timeout: 15s
  jms:
    listener:
      concurrency: 4
      max-concurrency: 8
#      acknowledge-mode: client

# spring boot 2.1.x use
    cache:
      enabled: true
      session-cache-size: 4
