debug: false

spring:

  activemq:
    broker-url: tcp://localhost:61616 #?jms.prefetchPolicy.queuePrefetch=1000
    in-memory: false
    pool:
      enabled: true
      time-between-expiration-check: 10s
      idle-timeout: 10s
  jms:
    listener:
      concurrency: 4
      max-concurrency: 8
      acknowledge-mode: client

#logging:
#  level:
#    root: warn
    
    